import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Sidbar from "@/components/SidBar/Sidbar";
import Navbar from "@/components/Navbar/Navbar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black h-screen overflow-hidden`}
      >
        <nav>
          <Navbar />
        </nav>
        <div className="flex flex-row bg-black px-5 md:px-12 xl:px-20">
          {/* sidebar */}
          <aside className="hidden lg:block">
            <Sidbar />
          </aside>
          <div className="flex-1 flex justify-center">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
